import { supabase } from '../lib/supabase'

// Interfaces for the new threading system
export interface ChatThread {
  id?: string // UUID, generated by database
  chat_interface_id: string // UUID linking to chat_interfaces
  title: string
  created_by_user_id?: string
  created_at?: string
  updated_at?: string
}

export interface ThreadMessage {
  id?: string // UUID, generated by database
  thread_id: string // UUID linking to chat_threads
  message_id: string // Frontend message ID for deduplication
  role: 'user' | 'assistant'
  content: string
  model?: string
  timestamp: string
  created_at?: string
}

export class ChatMessageLogger {
  // Log a new thread creation
  static async logThreadCreated(
    chatInterfaceId: string,
    frontendThreadId: string, // For mapping frontend state
    title: string = 'New Chat',
    userId?: string
  ): Promise<string | null> {
    if (!supabase) {
      console.log('Supabase not configured, skipping thread creation log')
      return null
    }

    try {
      const threadData: Omit<ChatThread, 'id' | 'created_at' | 'updated_at'> = {
        chat_interface_id: chatInterfaceId,
        title,
        created_by_user_id: userId
      }

      const { data, error } = await supabase
        .from('chat_threads')
        .insert([threadData])
        .select('id')
        .single()

      if (error) {
        console.error('Failed to log thread creation:', error)
        return null
      } else {
        const threadId = data.id
        console.log(`🧵 Logged thread creation: ${frontendThreadId} → DB: ${threadId}`)
        return threadId
      }
    } catch (err) {
      console.error('Error logging thread creation:', err)
      return null
    }
  }

  // Log a thread deletion
  static async logThreadDeleted(threadId: string): Promise<void> {
    if (!supabase) {
      console.log('Supabase not configured, skipping thread deletion log')
      return
    }

    try {
      const { error } = await supabase
        .from('chat_threads')
        .delete()
        .eq('id', threadId)

      if (error) {
        console.error('Failed to log thread deletion:', error)
      } else {
        console.log(`🗑️ Logged thread deletion: ${threadId}`)
      }
    } catch (err) {
      console.error('Error logging thread deletion:', err)
    }
  }

  // Log a thread title update
  static async logThreadTitleUpdate(
    threadId: string,
    newTitle: string
  ): Promise<void> {
    if (!supabase) {
      console.log('Supabase not configured, skipping thread title update')
      return
    }

    try {
      const { error } = await supabase
        .from('chat_threads')
        .update({ 
          title: newTitle,
          updated_at: new Date().toISOString()
        })
        .eq('id', threadId)

      if (error) {
        console.error('Failed to log thread title update:', error)
      } else {
        console.log(`📝 Updated thread title: ${threadId} -> "${newTitle}"`)
      }
    } catch (err) {
      console.error('Error logging thread title update:', err)
    }
  }

  // Log a new message to a thread
  static async logThreadMessage(
    threadId: string,
    messageId: string,
    role: 'user' | 'assistant',
    content: string,
    model?: string,
    timestamp?: Date
  ): Promise<void> {
    if (!supabase) {
      console.log('Supabase not configured, skipping message log')
      return
    }

    try {
      const messageData: Omit<ThreadMessage, 'id' | 'created_at'> = {
        thread_id: threadId,
        message_id: messageId,
        role,
        content,
        model,
        timestamp: (timestamp || new Date()).toISOString()
      }

      const { error } = await supabase
        .from('thread_messages')
        .insert([messageData])

      if (error) {
        // Check if it's a duplicate message (based on message_id + thread_id)
        if (error.code === '23505') { // Unique violation
          console.log(`🔄 Message ${messageId} already logged in thread ${threadId}, skipping`)
          return
        }
        console.error('Failed to log thread message:', error)
      } else {
        console.log(`💬 Logged ${role} message: ${messageId} in thread ${threadId}`)
      }

      // Update thread's updated_at timestamp
      await supabase
        .from('chat_threads')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', threadId)

    } catch (err) {
      console.error('Error logging thread message:', err)
    }
  }

  // Batch log multiple messages to a thread (useful for thread initialization)
  static async logThreadMessages(
    threadId: string,
    messages: Array<{
      messageId: string
      role: 'user' | 'assistant'
      content: string
      model?: string
      timestamp?: Date
    }>
  ): Promise<void> {
    if (!supabase) {
      console.log('Supabase not configured, skipping thread messages batch log')
      return
    }

    try {
      const messageData: Omit<ThreadMessage, 'id' | 'created_at'>[] = messages.map(msg => ({
        thread_id: threadId,
        message_id: msg.messageId,
        role: msg.role,
        content: msg.content,
        model: msg.model,
        timestamp: (msg.timestamp || new Date()).toISOString()
      }))

      const { error } = await supabase
        .from('thread_messages')
        .insert(messageData)

      if (error) {
        console.error('Failed to batch log thread messages:', error)
      } else {
        console.log(`💬 Batch logged ${messages.length} messages for thread ${threadId}`)
      }

      // Update thread's updated_at timestamp
      await supabase
        .from('chat_threads')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', threadId)

    } catch (err) {
      console.error('Error batch logging thread messages:', err)
    }
  }

  // Get thread statistics
  static async getThreadStats(threadId: string): Promise<{
    messageCount: number
    userMessages: number
    assistantMessages: number
    lastMessageAt?: string
  } | null> {
    if (!supabase) {
      console.log('Supabase not configured, cannot get thread stats')
      return null
    }

    try {
      const { data, error } = await supabase
        .from('thread_messages')
        .select('role, created_at')
        .eq('thread_id', threadId)
        .order('created_at', { ascending: false })

      if (error) {
        console.error('Failed to get thread stats:', error)
        return null
      }

      const userMessages = data.filter(m => m.role === 'user').length
      const assistantMessages = data.filter(m => m.role === 'assistant').length
      const lastMessageAt = data.length > 0 ? data[0].created_at : undefined

      return {
        messageCount: data.length,
        userMessages,
        assistantMessages,
        lastMessageAt
      }
    } catch (err) {
      console.error('Error getting thread stats:', err)
      return null
    }
  }

  // Get all threads for a chat interface
  static async getChatInterfaceThreads(chatInterfaceId: string): Promise<ChatThread[]> {
    if (!supabase) {
      console.log('Supabase not configured, cannot get threads')
      return []
    }

    try {
      const { data, error } = await supabase
        .from('chat_threads')
        .select('*')
        .eq('chat_interface_id', chatInterfaceId)
        .order('created_at', { ascending: false })

      if (error) {
        console.error('Failed to get chat interface threads:', error)
        return []
      }

      return data || []
    } catch (err) {
      console.error('Error getting chat interface threads:', err)
      return []
    }
  }

  // Get all messages for a thread
  static async getThreadMessages(threadId: string): Promise<ThreadMessage[]> {
    if (!supabase) {
      console.log('Supabase not configured, cannot get thread messages')
      return []
    }

    try {
      const { data, error } = await supabase
        .from('thread_messages')
        .select('*')
        .eq('thread_id', threadId)
        .order('created_at', { ascending: true })

      if (error) {
        console.error('Failed to get thread messages:', error)
        return []
      }

      return data || []
    } catch (err) {
      console.error('Error getting thread messages:', err)
      return []
    }
  }
}